package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
)

type AutoGenerated []struct {
	// autogenerated with https://mholt.github.io/json-to-go/
	Name       string        `json:"name"`
	Packages   []string      `json:"packages"`
	Status     string        `json:"status"`
	Severity   string        `json:"severity"`
	Type       string        `json:"type"`
	Affected   string        `json:"affected"`
	Fixed      interface{}   `json:"fixed"`
	Ticket     interface{}   `json:"ticket"`
	Issues     []string      `json:"issues"`
	Advisories []interface{} `json:"advisories"`
}

func main() {
	r, err := http.Get("https://security.archlinux.org/all.json")
	if err != nil {
		log.Fatal("Ops..we shouldn't be here")
	}
	defer r.Body.Close()
	if r.StatusCode == http.StatusOK {
		bodyBytes, _ := ioutil.ReadAll(r.Body)
		var m AutoGenerated
		err3 := json.Unmarshal(bodyBytes, &m)
		if err3 != nil {
			log.Fatal("Ops..")
		} else {
			log.Println(m[0])
		}
	}
}
